(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/") ("org" . "https://orgmode.org/elpa/") ("gnu" . "https://elpa.gnu.org/packages/") ("elpa" . "https://elpa.gnu.org/packages/") ("nongnu" . "https://elpa.nongnu.org/nongnu/")))
(package-initialize)
(unless package-archive-contents (package-refresh-contents))
(unless (package-installed-p 'use-package) (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t use-package-verbose t)
(tool-bar-mode -1) (menu-bar-mode -1) (scroll-bar-mode -1)
(setq inhibit-startup-message t) (global-display-line-numbers-mode t) (show-paren-mode t)
(setq make-backup-files nil auto-save-default nil create-lockfiles nil)
(set-face-attribute 'default nil :family "Fira Code" :height 140)
(load-theme 'monokai t)
(use-package ivy :diminish :bind (("C-s" . swiper)) :config (ivy-mode 1) (setq ivy-use-virtual-buffers t))
(use-package counsel :bind (("M-x" . counsel-M-x) ("C-x C-f" . counsel-find-file) ("C-x b" . counsel-switch-buffer)))
(use-package which-key :diminish which-key-mode :config (which-key-mode))
(use-package company :hook (prog-mode . company-mode) :config (setq company-idle-delay 0.2 company-minimum-prefix-length 2))
(use-package magit :bind ("C-x g" . magit-status))
(use-package projectile :diminish projectile-mode :config (projectile-mode +1) :bind (:map projectile-mode-map ("C-c p" . projectile-command-map)))
(use-package flycheck :hook (prog-mode . flycheck-mode))
(use-package python-mode :mode "\\.py\\'")
(use-package go-mode :mode "\\.go\\'")
(use-package evil :init (setq evil-want-integration t evil-want-keybinding nil) :config (evil-mode 1))
(use-package evil-collection :after evil :config (evil-collection-init))
(use-package ace-window :bind ("M-o" . ace-window) :config (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l)))
(global-set-key (kbd "C-x |") 'split-window-right)
(global-set-key (kbd "C-x -") 'split-window-below)
(global-set-key (kbd "C-x +") 'balance-windows)
(global-set-key (kbd "C-x x") 'delete-window)
(setq org-directory "~/Documents/org-roam/")
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c c") 'org-capture)
(setq projectile-project-search-path '("~/Documents/org-roam/"))
(use-package deft :bind ("C-c d" . deft-find-file) :config (setq deft-extensions '("org" "txt" "md") deft-directory org-directory deft-recursive t deft-use-filename-as-title t))
(use-package doom-modeline :init (doom-modeline-mode 1) :custom (doom-modeline-height 25) (doom-modeline-icon t))
(use-package all-the-icons :if (display-graphic-p))
